<a href="https://colab.research.google.com/github/Yong-Hui-Liew/PyTorch-Adventure/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

if you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)  #Torch version + CUDA version

2.2.1+cu121


In [ ]:
# Only using free GPU, with free Collab

## Introduction to Tensors

### Creating tensors

Pytorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensor.html

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [ ]:
vector.ndim  # no. of square brackets

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX
MATRIX.ndim


2

In [ ]:
 # Tensor
 TENSOR = torch.tensor([[[1, 2, 3],
                         [3, 6, 9],
                         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape  #the '1' means first bracket dimension

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Random tensors are important because they start with random numbers and update later

In [ ]:
# Create a random tensors of size (3,4)
random_tensor = torch.rand(3, 4)  # 2 dimensions
random_tensor

tensor([[0.5213, 0.1983, 0.9740, 0.0662],
        [0.7721, 0.5794, 0.0614, 0.0551],
        [0.7208, 0.6511, 0.1256, 0.2919]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #h x w x channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeroes and ones

In [ ]:
# Create a tensor of all zeroes
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.range()
one_to_ten = torch.arange(start=0, end=1000, step=77)   # Use torch.arange to avoid deprecation
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

 ### Tensor datatypes

 **Note:** Tensor datatypes are one of the 3 big errors you'll run into with PyTorch & Deep Learning:
 1. Tensors not right datatype
 2. Tensor not right shape
 3. Tensors not on the right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32,   # Many types available (float 16 and 32 more common)
                               device="cpu",  # or "cuda"
                               requires_grad=False)  # Pytorch tracking this tensor's gradients in backpropagation

In [ ]:
float_32_tensor.dtype   # A measure of the precision of floating-point number

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor   # Actually works even with different datatypes, but not always!

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
long_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
long_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensor (tensor attributes)

 1. Tensors not right datatype -> can check using `tensor.dtype`
 2. Tensor not right shape -> can use `tensor.shape`
 3. Tensors not on the right device -> can use `tensor.device`

In [ ]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2890, 0.7694, 0.0670, 0.1514],
        [0.8077, 0.6154, 0.9125, 0.5543],
        [0.3636, 0.0481, 0.4439, 0.6340]])

In [ ]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")   # some_tensor.size() gives same result
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.2890, 0.7694, 0.0670, 0.1514],
        [0.8077, 0.6154, 0.9125, 0.5543],
        [0.3636, 0.0481, 0.4439, 0.6340]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


In [ ]:
some_tensor.size()

torch.Size([3, 4])

### Manipulating Tensors (tensors operations)

Tensor operations include:
* Addiiton
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10   # Note: tensor variable is not reassigned

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10
tensor * 10
tensor

tensor([100, 200, 300])

In [ ]:
# Try out PyTorch in-built functions (torch.add, torch.mul, etc.)
torch.mul(tensor,10)

tensor([1000, 2000, 3000])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning

1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [ ]:
 # Element wise multiplication
 print(tensor, "*", tensor)
 print(f"Equals: {tensor * tensor}")

tensor([100, 200, 300]) * tensor([100, 200, 300])
Equals: tensor([10000, 40000, 90000])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)  # or use `tensor @ tensor`

tensor(140000)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value
print(value)

tensor(140000)
CPU times: user 3.13 ms, sys: 0 ns, total: 3.13 ms
Wall time: 4.28 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)  # Much faster than for loop


CPU times: user 1.11 ms, sys: 0 ns, total: 1.11 ms
Wall time: 1.13 ms


tensor(140000)

### One of the most common errors in deep learning: shape errors


In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
torch.mm(tensor_A, tensor_B)   # torch.mm is the same as torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix the shape issues, we can use a **transpose**

In [ ]:
torch.matmul(tensor_A, tensor_B.T)  # Using transpose ".T"

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum, etc (tensor aggregaton)

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x , x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
# Find the min
torch.min(x)  # Creates a smaller tensor with the min. value

tensor(0)

In [ ]:
# Find the max
torch.max(x)

tensor(90)

In [ ]:
# Find the mean
torch.mean(x.type(torch.float32))   # Only accepts floating point or complex dtypes (try running without typecast)

tensor(45.)

In [ ]:
x.type(torch.float32).mean()  # Alternative

tensor(45.)

In [ ]:
# Find the sum
torch.sum(x), x.sum()  # Two styles

(tensor(450), tensor(450))

## Finding the positional min and max


In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.argmin()   # index position of minimum value

tensor(0)

In [ ]:
x[0]

tensor(0)

In [ ]:
x.argmax()   # index position of maximum value

tensor(9)

In [ ]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# Create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(9, 1)   # must have same elements as previous tensor
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)   # Takes in a list of tensor and concatenates along a new dimension
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# Stack tensors side by side
x_stacked = torch.stack([x, x, x, x], dim=1)   # Takes in a list of tensor and concatenates along a new dimension
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target sensor
x = torch.zeros(2, 1, 2, 1, 2)
x_squeezed = torch.squeeze(x)
x.size(), x_squeezed.size()

(torch.Size([2, 1, 2, 1, 2]), torch.Size([2, 2, 2]))

In [ ]:
# torch.unsqueeze() - add a single dimension to a target tensor at a specific dim (dimension)
x_unsqueezed = x_squeezed.unsqueeze(dim=0)  # dim = 0: adds dimension to 0th position / dim = 1: adds dimensions to the last position
x_unsqueezed.shape

torch.Size([1, 2, 2, 2])

In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
# returns a view of the original tensor input with its dimensions permuted

x_original = torch.rand(size=(224, 224, 3))  # image data

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)  # view of x_original (try changing it to see if it affects)
x_permuted.shape

torch.Size([3, 224, 224])

## Indexing (selecting data from tensors)

Indexing with Pytorch is similar to indexing with Numpy

In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle bracket (dim=1)
x[0][0]  # Or x[0,0]

tensor([1, 2, 3])

In [ ]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [ ]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only 1st index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 9
x[0, 2, 2]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
# Index on x to return 3, 6, 9
x[0, :, 2]

tensor([3, 6, 9])

## Pytorch tensors & Numpy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`


In [ ]:
# NumPy array to tesor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)  # When converting from numpy -> pytorch, dtype changes to float64 (by default)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change the value of array, what will this do to `tensor` ? (Nothing, not a view)
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()  # dtype=float32 as this is tensor's default data type
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

In [ ]:
# Change the tensor, what happens to `numpy_tensor`? (Nothing. Not a view!)
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them bettter representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomess

In [ ]:
import torch

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7086, 0.0348, 0.9340, 0.0174],
        [0.5948, 0.6782, 0.0489, 0.0110],
        [0.6398, 0.8478, 0.6197, 0.6117]])
tensor([[0.3169, 0.6829, 0.2466, 0.2258],
        [0.3552, 0.8354, 0.2829, 0.1367],
        [0.4324, 0.4237, 0.7139, 0.9407]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)  # We must add the manual seed each time we call `rand`
random_tensor_C = torch.rand(3, 4)  # doesn't come with seed method

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C == random_tensor_D)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running tensor and PyTorch object on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good)

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - take a little bit of setup and requires the investment of purchasing a GPU, there's lots of options...
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 Pytorch + GPU drivers (CUDA) takes a lttle bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/


In [ ]:
!nvidia-smi

Fri May 24 00:26:58 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Check for GPU access with PyTorch

In [1]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code:
https://pytorch.org/docs/stable/notes/cuda.html#device-agnostic-code

E.g. run on GPU if available, else default to CPU

In [2]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [3]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations

In [5]:
tensor = torch.tensor([1, 2, 3])  # default device: cpu

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [6]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)  # `device` is conditional statement
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [7]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()  # Can't convert to numPy using GPU. Requires CPU (`.cpu()`)

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [8]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()   # `.cpu` converts GPU -> CPU
tensor_back_on_cpu

array([1, 2, 3])

In [9]:
tensor_back_on_cpu.gpu().numpy()   # but no `.gpu` command

AttributeError: 'numpy.ndarray' object has no attribute 'gpu'