<a href="https://colab.research.google.com/github/Yong-Hui-Liew/PyTorch-Adventure/blob/main/00_pytorch_exercise_solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Documentation reading
A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on `torch.Tensor` and for `torch.cuda`.

https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics
https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics

## Create a random tensor with shape (7, 7)

In [2]:
import torch
tensor = torch.rand(7,7)
tensor

tensor([[0.7184, 0.5225, 0.3149, 0.3876, 0.6358, 0.9052, 0.9449],
        [0.6455, 0.7202, 0.1182, 0.9389, 0.3083, 0.1467, 0.9998],
        [0.1063, 0.7797, 0.8543, 0.9569, 0.8418, 0.7567, 0.3409],
        [0.3606, 0.8115, 0.7256, 0.2246, 0.2505, 0.9370, 0.6343],
        [0.4789, 0.5443, 0.9210, 0.5778, 0.6446, 0.4738, 0.9352],
        [0.3556, 0.9014, 0.4891, 0.4140, 0.9761, 0.2529, 0.4539],
        [0.1994, 0.6945, 0.2744, 0.0816, 0.9434, 0.0630, 0.0169]])

## Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor)

In [3]:
tensor2 = torch.rand(1,7)
tensor_mul = torch.matmul(tensor, tensor2.T)
tensor_mul

tensor([[1.8695],
        [1.8992],
        [1.6359],
        [1.8719],
        [2.0993],
        [1.6566],
        [0.8668]])

## Set the random seed to 0 and do exercises 2 & 3 over again

In [4]:
RANDOM_SEED = 0

torch.manual_seed(RANDOM_SEED)
tensor = torch.rand(7,7)

torch.manual_seed(RANDOM_SEED)
tensor2 = torch.rand(1,7)

tensor_mul = torch.matmul(tensor, tensor2.T)
tensor, tensor2, tensor_mul

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]]),
 tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]))

## Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one). If there is, set the GPU random seed to 1234

In [5]:
torch.cuda.manual_seed(1234)

## Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [10]:
torch.manual_seed(1234)
tensor_rand = torch.rand(2,3).to("cuda")

torch.manual_seed(1234)
tensor_rand2 = torch.rand(2,3).to("cuda")

tensor_rand, tensor_rand2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'))

## Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors)

In [12]:
tensor_mul = torch.matmul(tensor_rand, tensor_rand2.T)
tensor_mul

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

## Find the maximum and minimum values of the output of 7

In [14]:
print(tensor_mul.max())
print(tensor_mul.min())

tensor(0.6287, device='cuda:0')
tensor(0.2161, device='cuda:0')


## Find the maximum and minimum index values of the output of 7

In [16]:
print(tensor_mul.argmin())
print(tensor_mul.argmax())

tensor(1, device='cuda:0')
tensor(3, device='cuda:0')


## Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape

In [25]:
tensor_rand = torch.rand(1, 1, 1, 10)
print(tensor_rand, tensor_rand.shape)
torch.manual_seed(7)
tensor_squeezed = tensor_rand.squeeze()
print(tensor_squeezed, tensor_squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
